# /etc/rspamd/local.d/dkim_signing.conf
# Keys are created per-domain by `panelctl mail:domain:add`.
path = "/var/lib/rspamd/dkim/$domain.$selector.key";
selector = "mail";
allow_username_mismatch = true;
use_domain = "header";
sign_authenticated = true;
try_fallback = false;
