# HostingPanel admin UI — regenerated by `panelctl panel:domain`.
Listen 8443
<VirtualHost *:8443>
    ServerName {{server_name}}
    DocumentRoot /opt/hostingpanel/panel/public

    SSLEngine on
    SSLCertificateFile {{cert}}
    SSLCertificateKeyFile {{key}}
    SSLProtocol -all +TLSv1.2 +TLSv1.3

    <Directory /opt/hostingpanel/panel/public>
        Options -Indexes
        AllowOverride None
        Require all granted

        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [QSA,L]
    </Directory>

    Alias /phpmyadmin /opt/hostingpanel/phpmyadmin
    <Directory /opt/hostingpanel/phpmyadmin>
        Options -Indexes
        AllowOverride None
        Require all granted
    </Directory>

    Alias /webmail /opt/hostingpanel/webmail
    <Directory /opt/hostingpanel/webmail>
        Options -Indexes
        AllowOverride None
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php/hostingpanel.sock|fcgi://localhost"
    </FilesMatch>

    ErrorLog ${APACHE_LOG_DIR}/hostingpanel-error.log
    CustomLog ${APACHE_LOG_DIR}/hostingpanel-access.log combined
</VirtualHost>
